Import("env")

from pathlib import Path
import re
import subprocess
import shutil


ROOT = Path(env["PROJECT_DIR"])
OUT_PATH = ROOT / "include" / "BuildInfo.h"
BASE_PATH = ROOT / "include" / "FwBaseVersion.h"


def _run_git(args):
    return subprocess.check_output(["git"] + args, cwd=ROOT, stderr=subprocess.STDOUT, text=True).strip()


def _read_minor():
    if not BASE_PATH.exists():
        return 0
    text = BASE_PATH.read_text(encoding="utf-8")
    match = re.search(r"CCR_FW_MINOR\s+(\d+)", text)
    if not match:
        return 0
    try:
        return int(match.group(1))
    except ValueError:
        return 0


def _read_git_build():
    if not (ROOT / ".git").exists() or not shutil.which("git"):
        return None
    try:
        _run_git(["rev-parse", "--is-inside-work-tree"])
        count = _run_git(["rev-list", "--count", "HEAD"])
        return int(count)
    except Exception:
        return None


def _compute_version():
    minor = _read_minor()
    build = _read_git_build()
    if build is None:
        build = 0
    return f"0.1.{minor}.{build:07d}"


def _write_header(version):
    content = (
        "#pragma once\n"
        "\n"
        "// Auto-generated by scripts/gen_version.py\n"
        f"#define CCR_FW_VERSION_STR \"{version}\"\n"
    )
    if OUT_PATH.exists():
        existing = OUT_PATH.read_text(encoding="utf-8")
        if existing == content:
            return
    OUT_PATH.write_text(content, encoding="utf-8")


version = _compute_version()
_write_header(version)
