Import("env")

from pathlib import Path
import os
import re
import subprocess
import shutil


ROOT = Path(env["PROJECT_DIR"])
OUT_PATH = ROOT / "include" / "AutoVersion.generated.h"


def _run_git(args):
    return subprocess.check_output(["git"] + args, cwd=ROOT, stderr=subprocess.STDOUT, text=True).strip()


def _read_fallback_version():
    fallback_file = ROOT / "version_fallback.txt"
    if not fallback_file.exists():
        return None
    text = fallback_file.read_text(encoding="utf-8").strip()
    if not text:
        return None
    return text


def _compute_version():
    prefix_major = 0
    prefix_minor = 1

    env_minor = os.getenv("CCR_VERSION_MINOR")
    env_build = os.getenv("CCR_VERSION_BUILD")

    default_minor = 0
    default_build = 0
    if env_minor is not None:
        try:
            default_minor = int(env_minor)
        except ValueError:
            default_minor = 0
    if env_build is not None:
        try:
            default_build = int(env_build)
        except ValueError:
            default_build = 0

    if (ROOT / ".git").exists() and shutil.which("git"):
        try:
            _run_git(["rev-parse", "--is-inside-work-tree"])
            tag = _run_git(["describe", "--tags", "--match", "v0.1.*", "--abbrev=0"])
        except Exception:
            tag = ""

        if tag:
            match = re.match(r"v0\.1\.(\d+)$", tag)
            if match:
                minor = int(match.group(1))
            else:
                minor = default_minor
            try:
                build = int(_run_git(["rev-list", "--count", f"{tag}..HEAD"]))
            except Exception:
                build = default_build
        else:
            minor = default_minor
            try:
                build = int(_run_git(["rev-list", "--count", "HEAD"]))
            except Exception:
                build = default_build
    else:
        fallback = _read_fallback_version()
        if fallback:
            return fallback
        minor = default_minor
        build = default_build

    return f"{prefix_major}.{prefix_minor}.{minor}.{build:07d}"


def _write_header(version):
    content = (
        "#pragma once\n"
        "\n"
        "// Auto-generated by scripts/gen_version.py\n"
        f"#define FW_VERSION_STR \"{version}\"\n"
    )
    if OUT_PATH.exists():
        existing = OUT_PATH.read_text(encoding="utf-8")
        if existing == content:
            return
    OUT_PATH.write_text(content, encoding="utf-8")


version = _compute_version()
_write_header(version)
